runs:
  using: "composite"
  steps:

    - name: Run Unit Tests And Code Coverage (DEBUG)
      shell: bash
      run: ./gradlew :clevertap-core:jacocoTestReportDebug :clevertap-geofence:jacocoTestReportDebug  :clevertap-hms:jacocoTestReportDebug  :clevertap-pushTemplates:jacocoTestReportDebug :clevertap-xps:jacocoTestReportDebug

    - name: Upload Unit tests
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-results
        path: |
          clevertap-core/build/reports/tests
          clevertap-core/build/reports/jacoco

          clevertap-hms/build/reports/tests
          clevertap-hms/build/reports/jacoco

          clevertap-xps/build/reports/tests
          clevertap-xps/build/reports/jacoco

          clevertap-geofence/build/reports/tests
          clevertap-geofence/build/reports/jacoco

          clevertap-pushtemplates/build/reports/tests
          clevertap-pushtemplates/build/reports/jacoco



      #todo : set success/failure as output and use slack action to send message . setting success failure: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions
