name: validate PR raised from develop branched to master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  lint-static_checks-test-build:
    if: github.head_ref == 'develop'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the code from Repo
        uses: actions/checkout@v2

      - name: Mandatory File Changes
        uses: ./.github/mini_flows/s1_mandatory_filechanges

      - name: Setup JDK 11.
        uses: ./.github/mini_flows/s2_setup_jdk

      - name: Run lint tests and Upload results
        uses: ./.github/mini_flows/s3_lint

      - name: Static Code Check Via detekt
        uses: ./.github/mini_flows/s4_detekt

      - name: Static Code Check Via checkstyle
        uses: ./.github/mini_flows/s5_checkstyle

      - name: Unit Tests and Jacoco Coverage (DEBUG AND RELEASE)
        uses: ./.github/mini_flows/s6_test_coverage

      - name: Build Code
        uses: ./.github/mini_flows/s7_build
